### PR TITLE
:bug: fix: fix misspelled manifest entry

### PR DESCRIPTION
**Pull request by tonywu6**
- Fix misspelled `server_worker` in code and types, should be `service_worker` instead
- Remove `types/chromeManifest` because `@types/chrome` already comes with typing for manifest.json via `chrome.runtime.Manifest`

### CODE REVIEW

**Comment by arvinxx** [comment]
> Fix misspelled server_worker in code and types, should be service_worker instead

Thanks for your correct.


> Remove types/chromeManifest because @types/chrome already comes with typing for manifest.json via chrome.runtime.Manifest

please don't remove it. Because defined is used in umi plugin config defination.Beside it's also used to auto geneate document.

**Comment by tonywu6** [comment]
@arvinxx I've reverted all changes related to `chrome.runtime.Manifest` (will open a new issue for that)

**Comment by arvinxx** [comment]
close #630

**Comment by arvinxx** [comment]
Thanks for your nice working!~

**Pull request merged**
